language: r
sudo: false
cache: packages

r:
  - oldrel
  - release
  - devel

# Mac OS X specific config is defined in matrix.include hereunder
os:
  - linux
  #- osx # Disable MacOS X for now  - osx

branches:
  only:
    - master
#    - macosx

# This is used to compact and check size of vignettes
addons:
  apt:
    update: true
    packages:
      - libgs-dev
      - qpdf
      - ghostscript

# Be strict when checking our package, but don't build the manual
warnings_are_errors: true
# Don't build vignettes on Mac OS X
r_build_args: --no-manual --no-resave-data --compact-vignettes=gs+qpdf
r_check_args: --no-manual --as-cran
disable_homebrew: true

#matrix:
#  include:
#    - os: osx
#      r_build_args: --no-manual --no-build-vignettes --no-resave-data
#      r_check_args: --no-manual --no-build-vignettes

# Email notifications
notifications:
  email:
    on_success: change
    on_failure: change

# covr is not a dependency for the package. So, install it explicitly
# RUnit required for Rd xref checking. Also force its install
#r_binary_packages:
#  - covr
#  - RUnit

after_success:
  - Rscript -e 'covr::codecov()'
